name: MineSuiteTeleport
version: ${project.version}
description: TeleportPlugin
authors: [Kekshaus]
main: de.linzn.mineSuite.teleport.TeleportPlugin
load: POSTWORLD
depend: [MineSuiteCore]
api-version: 1.13
commands:
  setspawn:
    description: Set a SpawnType
  unsetspawn:
    description: Unset a SpawnType
  lobby:
    description: Teleport to Lobby.
    aliases: [hub, proxyspawn, globalspawn, gs]
  spawn:
    description: Teleport to a SpawnType.
    aliases: [ss, ws, serverspawn, worldspawn]
  tp:
    description: Delete a SpawnType
  tphere:
    description: Delete a SpawnType
  back:
    description: Delete a SpawnType
  tpahere:
    description: Delete a SpawnType
  tpa:
    description: Delete a SpawnType
  tpaccept:
    description: Delete a SpawnType
  tpdeny:
    description: Delete a SpawnType
permissions:
    mineSuite.teleport.team:
        description: Alle Permissions
        children:
            mineSuite.teleport.user: true
            mineSuite.teleport.setspawn: true
            mineSuite.teleport.tp: true
            mineSuite.teleport.tphere: true
    mineSuite.teleport.user:
        description: Alle Permissions
        children:
            mineSuite.teleport.lobby: true
            mineSuite.teleport.spawn: true
            mineSuite.teleport.back: true
            mineSuite.teleport.tpa: true
            mineSuite.teleport.tpahere: true
            mineSuite.teleport.tpaccept: true
            mineSuite.teleport.tpdeny: true
    mineSuite.teleport.lobby:
        description: Teleport to lobby
        default: op
    mineSuite.teleport.setspawn:
        description: Teleport to lobby
        default: op
    mineSuite.teleport.spawn:
        description: Teleport to spawn
        default: op
    mineSuite.teleport.back:
        description: Teleport to spawn
        default: op
    mineSuite.teleport.tp:
        description: Teleport to spawn
        default: op
    mineSuite.teleport.tphere:
        description: Teleport to spawn
        default: op
    mineSuite.teleport.tpa:
        description: Teleport to spawn
        default: op
    mineSuite.teleport.tpahere:
        description: Teleport to spawn
        default: op
    mineSuite.teleport.tpaccept:
        description: Teleport to spawn
        default: op
    mineSuite.teleport.tpdeny:
        description: Teleport to spawn
        default: op