name: XeonSuiteTeleport
version: ${project.version}.b${build.number}
description: Teleportplugin
authors: [Kekshaus]
main: de.nlinz.xeonSuite.teleport.Teleportplugin
load: POSTWORLD
depend: [XeonSuiteBukkit]

commands:
  setspawn:
    description: Set a SpawnType serverspawn
  setlobby:
    description: Set a SpawnType lobby
  lobby:
    description: Teleport to Lobby.
    aliases: [hub, proxyspawn, globalspawn, gs]
  spawn:
    description: Teleport to a SpawnType.
    aliases: [ss, ws, serverspawn, worldspawn]
  dellobby:
    description: Delete a SpawnType
  delspawn:
    description: Delete a SpawnType
  tp:
    description: Delete a SpawnType
  tphere:
    description: Delete a SpawnType
  back:
    description: Delete a SpawnType
  tpahere:
    description: Delete a SpawnType
  tpa:
    description: Delete a SpawnType
  tpaccept:
    description: Delete a SpawnType
  tpdeny:
    description: Delete a SpawnType
permissions:
    xeonSuite.teleport.team:
        description: Alle Permissions
        children:
            xeonSuite.teleport.user: true
            xeonSuite.teleport.setspawn: true
            xeonSuite.teleport.delspawn: true
            xeonSuite.teleport.dellobby: true
            xeonSuite.teleport.setlobby: true
            xeonSuite.teleport.tp: true
            xeonSuite.teleport.tphere: true
    xeonSuite.teleport.user:
        description: Alle Permissions
        children:
            xeonSuite.teleport.lobby: true
            xeonSuite.teleport.spawn: true
            xeonSuite.teleport.back: true
            xeonSuite.teleport.tpa: true
            xeonSuite.teleport.tpahere: true
            xeonSuite.teleport.tpaccept: true
            xeonSuite.teleport.tpdeny: true
    xeonSuite.teleport.lobby:
        description: Teleport to lobby
        default: op
    xeonSuite.teleport.setspawn:
        description: Teleport to lobby
        default: op
    xeonSuite.teleport.setlobby:
        description: Teleport to lobby
        default: op
    xeonSuite.teleport.delspawn:
        description: Teleport to lobby
        default: op
    xeonSuite.teleport.dellobby:
        description: Teleport to lobby
        default: op
    xeonSuite.teleport.spawn:
        description: Teleport to spawn
        default: op
    xeonSuite.teleport.back:
        description: Teleport to spawn
        default: op
    xeonSuite.teleport.tp:
        description: Teleport to spawn
        default: op
    xeonSuite.teleport.tphere:
        description: Teleport to spawn
        default: op
    xeonSuite.teleport.tpa:
        description: Teleport to spawn
        default: op
    xeonSuite.teleport.tpahere:
        description: Teleport to spawn
        default: op
    xeonSuite.teleport.tpaccept:
        description: Teleport to spawn
        default: op
    xeonSuite.teleport.tpdeny:
        description: Teleport to spawn
        default: op